### ISSUE TITLE
How to use CS2ASM?

### ISSUE THREAD

**Issue by saluransains** [nifanfa/CS2ASM#8]
### Discussed in https://github.com/nifanfa/CS2ASM/discussions/7

<div type='discussions-op-text'>

<sup>Originally posted by **saluransains** January 31, 2022</sup>
How to use CS2ASM?</div>

**Comment by nifanfa** [comment]
Select consoleApp1 in visual studio solution explorer and press f5

**Comment by nifanfa** [comment]
checkout consoleapp1/properties/launchsettings.json

**Comment by saluransains** [comment]
Thanks
